Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('umk/',include('umk.urls', namespace='umk')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

umk/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from .views import  InstituteListView, InstituteDetailView,InstituteCreateView,InstituteUpdateView,InstituteDeleteView 
from .views import  DirectionListView, DirectionDetailView,DirectionCreateView,DirectionUpdateView,DirectionDeleteView 
from . import views

app_name = 'UMK'
urlpatterns = [
    #path('institutes/',views.get_institutes, name='institutes'),
    #path('directions/',views.get_directions, name='directions'),
    path('get_document/<int:file_id>/', views.get_document, name ='document'),
    path('institutes/', InstituteListView.as_view(), name='institutes'),
    path('institutes/new/', InstituteCreateView.as_view(), name='institute_new'),
    path('institutes/<int:pk>/', InstituteDetailView.as_view(), name='institute_detail'),
    path('institutes/<int:pk>/edit/',InstituteUpdateView.as_view(), name = 'institute_edit'),
    path('institutes/<int:pk>/delete/',InstituteDeleteView.as_view(), name = 'institute_delete'),
    path('directions/', DirectionListView.as_view(), name='directions'),
    path('directions/generate/', views.downloadWord, name='generate'),
    path('directions/new/', DirectionCreateView.as_view(), name='direction_new'),
    path('directions/<int:pk>/', DirectionDetailView.as_view(), name='direction_detail'),
    path('directions/<int:pk>/edit/',DirectionUpdateView.as_view(), name = 'direction_edit'),
    path('directions/<int:pk>/delete/',DirectionDeleteView.as_view(), name = 'direction_delete'),
    

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/direction/direction_delete.html
{% extends 'base.html' %}
 
{% block content %}
    <h1>Удаление института</h1>
    <form action="" method="post">{% csrf_token %}
      <p>Вы уверены, что хотите удалить "{{object.name}}"?</p>
      <input type="submit" value="Confirm" />
    </form>
{% endblock content %}

templates/direction/direction_detail.html

{% extends "base.html" %}

{% block content %}

    <a href="{% url 'umk:institute_edit' object.pk %}">Редактировать данные о институте</a>
    <p><a href="{% url 'umk:institute_delete' object.pk %}">Удалить институт</a></p>
    <a href="">{{ object.name }}</a>
    <p>{{ object.info }}</p>



{% endblock %}


templates/direction/direction_edit.html
{% extends 'base.html' %}
 
{% block content %}
    <h1>Изменение данных о институте</h1>
    <form action="" method="post">{% csrf_token %}
      {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
{% endblock content %}

templates/direction/direction_new.html
{% extends 'base.html' %}
 
{% block content %}
    <h1>Новое направление подготовки</h1>
    <form action="" method="post">{% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Save" />
    </form>
{% endblock content %}

templates/direction/directions.html
{% extends "base.html" %}
{% block title %}Направления подготовки{% endblock %}

{% block content %}

<a href="{% url 'umk:direction_new' %}">Добавить направление подготовки</a><br>
<a href="{% url 'umk:generate' %}">генерировать</a><br>
{% for direction in object_list %}



<p>{{ direction.name }}</p>
<p>{{ direction.code }}</p>
<a href="{% url 'umk:document' direction.id %}"><button > ФГОС</button></a>


<p>{{ direction.qualification }}</p>

<p>{{ direction.standart_period}}</p>

{% endfor %}

{% endblock %}